apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: azurekeyvaultsubscriptions.horizon.ninoparisi.io
spec:
  group: horizon.ninoparisi.io
  names:
    kind: AzureKeyVaultSubscription
    listKind: AzureKeyVaultSubscriptionList
    plural: azurekeyvaultsubscriptions
    singular: azurekeyvaultsubscription
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          status:
            nullable: false
            type: object
            properties:
              status:
                nullable: false
                type: string
          spec:
            nullable: false
            type: object
            properties:
              vaults:
                type: array
                items:
                  type: object
                  properties:
                    azureKeyVaultName:
                      nullable: false
                      type: string
                    secretPrefix:
                      nullable: false
                      type: string
                    k8sSecretObjectName:
                      nullable: false
                      type: string
    served: true
    storage: true
    subresources:
      status: {}