apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: azurekeyvaultsubscriptions.horizon.sh
spec:
  group: horizon.sh
  names:
    kind: AzureKeyVaultSubscription
    listKind: AzureKeyVaultSubscriptionList
    plural: azurekeyvaultsubscriptions
    singular: azurekeyvaultsubscription
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            nullable: false
            properties:
              status:
                nullable: false
                type: string
            type: object
          spec:
            nullable: false
            items:
              properties:
                azureKeyVaultUrl:
                  nullable: false
                  type: string
                k8sSecretObjectName:
                  nullable: false
                  type: string
              type: object
            type: array
        type: object
    served: true
    storage: true
    subresources:
      status: {}