apiVersion: horizon.ninoparisi.io/v1
kind: HorizonProviderConfiguration
metadata:
  name: horizon-config
spec:
  azureKeyVaultAuthentication:
    type: ManagedIdentity
  webhookAuthentication:
    type: Basic
    username: admin
    password: password