apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: horizonproviderconfigurations.horizon.ninoparisi.io
spec:
  group: horizon.ninoparisi.io
  names:
    kind: HorizonProviderConfiguration
    plural: horizonproviderconfigurations
    singular: horizonproviderconfiguration
    listKind: HorizonProviderConfigurationList
  scope: Cluster
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              azureKeyVaultAuthentication:
                type: object
                properties:
                  type:
                    type: string
              webhookAuthentication:
                type: object
                properties:
                  type:
                    type: string
                  username:
                    type: string
                    nullable: true
                  password:
                    type: string
                    nullable: true
                  tenantId:
                    type: string
                    nullable: true
                  clientId:
                    type: string
                    nullable: true
            required:
              - azureKeyVaultAuthentication
              - webhookAuthentication