name: Continous Integration

permissions:
  pull-requests: write

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~\sonar\cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Install SonarCloud scanners
      run: |
        dotnet tool install --global dotnet-sonarscanner

    - name: Install dotnet-coverage
      run: |
        dotnet tool install --global dotnet-coverage

    - name: Restore dependencies
      run: dotnet restore src

    - name: Build the project
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        dotnet-sonarscanner begin /k:"tabman83_horizon" /o:"tabman83" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.scanner.scanAll=false /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
        dotnet build src --no-restore --configuration Debug
        dotnet-coverage collect "dotnet test src --no-build --verbosity normal --configuration Debug" -f xml -o "coverage.xml"
        dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
